### PR TITLE
feat(ci): scaffolding Ci workflow

### PR DESCRIPTION
**Pull request by mtulio**
Scaffolding CI workflow. Only lint tests were implemented.

Screenshot from 2022-06-01 19-01-51

Initial work for https://issues.redhat.com/browse/SPLAT-497

### CODE REVIEW

**Comment by mtulio** [comment]
@rvanderp3  @bostrt ptal?
/assign @bostrt

**Comment by bostrt** [comment]
Since the golang implementation will be used at GA, do you think we should still be testing `openshift-provider-cert` script in here?

**Comment by bostrt** [comment]
Besides the one question about the `openshift-provider-cert` script, the rest of this looks good to me for scaffolding.

**Comment by mtulio** [comment]
@bostrt thanks! I removed the TODOs to keep them on the related PRs. Keeping the flow with linters only, what we need to move the existing PRs.

**Pull request merged**
