### PR TITLE
OPCT-246: Introducing must-gather-monitoring to collect metrics

### PR DESCRIPTION
**Pull request by mtulio**
Introduce a must-gather-like collector to extract metrics from Prometheus.

The image for the custom must-gather (must-gather-monitoring) will be triggered by the artifact collector plugin, compacting all the metrics into a single compressed tarball file.

The metrics collected by default are extracted from the main widgets in the OCP Dashboards, prioritizing elaborated expressions to save storage in client side, and CPU and Memory in the server side.

The total of storage incremented in the final tarball file are less than 1MiB in the samples collected. o/

There are no tool to read and process the raw metrics yet, but it can be consumed in the future by the OPCT report or use opensource projects to load/back fill prometheus db to read it in the monitoring-like tools (anyone that requires lower development effort would be preferred). 

Additional storage for default metrics collected:

```bash
$ ls -sh results/plugins/99-openshift-artifacts-collector/results/global/artifacts_must-gather-metrics.tar.xz
464K results/plugins/99-openshift-artifacts-collector/results/global/artifacts_must-gather-metrics.tar.xz
$ tar xfJ results/plugins/99-openshift-artifacts-collector/results/global/artifacts_must-gather-metrics.tar.xz -C metrics/
$ du -sh metrics/
532K	metrics/
$ tree metrics/
metrics/
└── monitoring
    ├── event-filter.html
    ├── prometheus
    │   ├── metrics
    │   │   ├── query_range-api-kas-request-duration-p99.json.gz
    │   │   ├── query_range-api-kas-request-duration-p99.stderr
    │   │   ├── query_range-cluster-cpu-usage.json.gz
    │   │   ├── query_range-cluster-cpu-usage.stderr
    │   │   ├── query_range-cluster-memory-usage-wo-cache.json.gz
    │   │   ├── query_range-cluster-memory-usage-wo-cache.stderr
    │   │   ├── query_range-cluster-storage-iops.json.gz
    │   │   ├── query_range-cluster-storage-iops.stderr
    │   │   ├── query_range-cluster-storage-throughput.json.gz
    │   │   ├── query_range-cluster-storage-throughput.stderr
    │   │   ├── query_range-etcd-disk-fsync-db-duration-p99.json.gz
    │   │   ├── query_range-etcd-disk-fsync-db-duration-p99.stderr
    │   │   ├── query_range-etcd-disk-fsync-wal-duration-p10.json.gz
    │   │   ├── query_range-etcd-disk-fsync-wal-duration-p10.stderr
    │   │   ├── query_range-etcd-disk-fsync-wal-duration-p50.json.gz
    │   │   ├── query_range-etcd-disk-fsync-wal-duration-p50.stderr
    │   │   ├── query_range-etcd-disk-fsync-wal-duration-p80.json.gz
    │   │   ├── query_range-etcd-disk-fsync-wal-duration-p80.stderr
    │   │   ├── query_range-etcd-disk-fsync-wal-duration-p99.json.gz
    │   │   ├── query_range-etcd-disk-fsync-wal-duration-p99.stderr
    │   │   ├── query_range-etcd-peer-round-trip-time.json.gz
    │   │   ├── query_range-etcd-peer-round-trip-time.stderr
    │   │   ├── query_range-etcd-request-duration-p99.json.gz
    │   │   ├── query_range-etcd-request-duration-p99.stderr
    │   │   ├── query_range-etcd-total-leader-elections-day.json.gz
    │   │   ├── query_range-etcd-total-leader-elections-day.stderr
    │   │   ├── query_range-node-cpu-saturation-load1.json.gz
    │   │   ├── query_range-node-cpu-saturation-load1.stderr
    │   │   ├── query_range-node-disk-saturation.json.gz
    │   │   ├── query_range-node-disk-saturation.stderr
    │   │   ├── query_range-node-memory-saturation.json.gz
    │   │   ├── query_range-node-memory-saturation.stderr
    │   │   ├── query_range-node-network-saturation-rx.json.gz
    │   │   ├── query_range-node-network-saturation-rx.stderr
    │   │   ├── query_range-node-network-saturation-tx.json.gz
    │   │   └── query_range-node-network-saturation-tx.stderr
    │   └── query_range.log
    └── timestamp
```

https://issues.redhat.com/browse/OPCT-246

### CODE REVIEW

**Comment by mtulio** [comment]
ptal?
/assign @rvanderp3 @faermanj

**Comment by mtulio** [comment]
/hold
found a conflict

**Comment by rvanderp3** [comment]
/lgtm
/approve

nice enhancement

**Pull request merged**
